# Generated by Django 4.0.6 on 2023-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
                ('classstart', models.IntegerField()),
                ('classend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
                ('classstart', models.IntegerField()),
                ('classend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
                ('classstart', models.IntegerField()),
                ('classend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
                ('classstart', models.IntegerField()),
                ('classend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
                ('classstart', models.IntegerField()),
                ('classend', models.IntegerField()),
            ],
        ),
    ]
