# Generated by Django 4.0.6 on 2023-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='classend',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='friday',
            name='classstart',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monday',
            name='classend',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monday',
            name='classstart',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='classend',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='classstart',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='classend',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='classstart',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='classend',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='classstart',
            field=models.CharField(max_length=32),
        ),
    ]
