# Generated by Django 4.0.6 on 2023-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_disfriday_dismonday_disthursday_distuesday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='matters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thematter', models.CharField(max_length=32)),
            ],
        ),
    ]
