# Generated by Django 4.0.6 on 2023-05-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_matters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='matters',
            new_name='thematters',
        ),
    ]
