# Generated by Django 4.0.6 on 2023-05-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_matters_thematters'),
    ]

    operations = [
        migrations.CreateModel(
            name='theattendants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theattendant', models.CharField(max_length=32)),
            ],
        ),
    ]
