# Generated by Django 4.2.1 on 2023-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_pictest_delete_bgimg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PicTest",
        ),
    ]
