# Generated by Django 4.2.1 on 2023-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_scelectedbg"),
    ]

    operations = [
        migrations.CreateModel(
            name="masterattendants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("masterattendant", models.CharField(max_length=32)),
            ],
        ),
    ]
