# Generated by Django 4.2.1 on 2023-05-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_masterattendants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="masterattendants",
        ),
        migrations.AddField(
            model_name="theattendants",
            name="master",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
